name: "Setup anchor-cli"
description: "Install Anchor CLI via avm"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install Anchor CLI via avm
      run: |
        cargo install --git https://github.com/coral-xyz/anchor avm --force
        avm install ${{ env.ANCHOR_CLI_VERSION }}
        avm use ${{ env.ANCHOR_CLI_VERSION }}
        echo "$HOME/.avm/bin" >> $GITHUB_PATH
      shell: bash
